const DB='sn-revenue-test',STORE='state',KEY='v1';
let state={rows:[],tags:{}};let view='dashboard';
const $=id=>document.getElementById(id),clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const esc=s=>clean(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const eur=v=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(v)||0);
const num=v=>{if(typeof v==='number')return v;let s=clean(v).replace(/€/g,'').replace(/\s/g,'');if(s.includes(',')&&s.includes('.'))s=s.lastIndexOf(',')>s.lastIndexOf('.')?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'');else if(s.includes(','))s=s.replace(',','.');let n=Number(s);return Number.isFinite(n)?n:0};
function db(){return new Promise((ok,no)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function load(){let d=await db();state=await new Promise((ok,no)=>{let r=d.transaction(STORE).objectStore(STORE).get(KEY);r.onsuccess=()=>ok(r.result||state);r.onerror=()=>no(r.error)});d.close()}
async function save(){let d=await db();await new Promise((ok,no)=>{let t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(state,KEY);t.oncomplete=ok;t.onerror=()=>no(t.error)});d.close()}
function parseDate(v){if(typeof v==='number'){let d=new Date(Date.UTC(1899,11,30)+Math.round(v*86400000));return d.toISOString().slice(0,10)}let s=clean(v);if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);let m=s.match(/^(\d{1,2})[-/.](\d{1,2})[-/.](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:s}
async function xlsx(file){let z=await JSZip.loadAsync(await file.arrayBuffer()),p=new DOMParser(),w=p.parseFromString(await z.file('xl/workbook.xml').async('string'),'application/xml'),rels=p.parseFromString(await z.file('xl/_rels/workbook.xml.rels').async('string'),'application/xml'),rm={};rels.querySelectorAll('Relationship').forEach(r=>rm[r.getAttribute('Id')]=r.getAttribute('Target'));let sheets=[...w.querySelectorAll('sheet')].map(s=>({n:s.getAttribute('name'),id:s.getAttribute('r:id')||s.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id')})),sh=sheets.find(s=>s.n.toLowerCase()==='combined')||sheets[0],t=rm[sh.id];t=t.startsWith('/')?t.slice(1):(t.startsWith('xl/')?t:'xl/'+t.replace(/^\.\//,''));let ss=[];if(z.file('xl/sharedStrings.xml')){let sx=p.parseFromString(await z.file('xl/sharedStrings.xml').async('string'),'application/xml');sx.querySelectorAll('si').forEach(si=>ss.push([...si.querySelectorAll('t')].map(x=>x.textContent||'').join('')))}let xml=p.parseFromString(await z.file(t).async('string'),'application/xml'),rows=[];for(let rr of xml.querySelectorAll('sheetData > row')){let a=[];for(let c of rr.querySelectorAll(':scope > c')){let ref=c.getAttribute('r')||'A1',letters=(ref.match(/[A-Z]+/)||['A'])[0],i=0;for(let ch of letters)i=i*26+ch.charCodeAt(0)-64;i--;let type=c.getAttribute('t'),v=c.querySelector(':scope > v'),val='';if(type==='s'&&v)val=ss[Number(v.textContent)]??'';else if(type==='inlineStr')val=[...c.querySelectorAll('is t')].map(x=>x.textContent||'').join('');else if(v){let q=v.textContent,n=Number(q);val=q!==''&&Number.isFinite(n)?n:q}a[i]=val}rows.push(a)}return rows}
function csv(text){let d=(text.split(/\r?\n/)[0]||'').includes(';')?';':',',out=[],row=[],f='',q=false;for(let i=0;i<text.length;i++){let c=text[i];if(q){if(c==='"'&&text[i+1]==='"'){f+='"';i++}else if(c==='"')q=false;else f+=c}else if(c==='"')q=true;else if(c===d){row.push(f);f=''}else if(c==='\n'){row.push(f.replace(/\r$/,''));out.push(row);row=[];f=''}else f+=c}if(f||row.length){row.push(f);out.push(row)}return out}
const aliases={'year':'year','quarter':'quarter','company':'company','date':'date','account':'account','customer':'customer','invoice nr':'invoice','invoice no':'invoice','invoice number':'invoice','description':'description','revenue (eur)':'revenue','revenue':'revenue','revenue incl vat (eur)':'incl','country':'country','industry':'industry','product group':'group','product type':'type','supplier':'supplier'};
function records(rows){if(!rows.length)return[];let h=rows[0].map(x=>aliases[clean(x).toLowerCase()]||clean(x).toLowerCase()),idx={};h.forEach((x,i)=>idx[x]=i);if(idx.company==null||idx.date==null||idx.revenue==null)throw Error('Kolommen Company, Date en Revenue (EUR) zijn verplicht.');let g=(r,k)=>idx[k]==null?'':r[idx[k]];return rows.slice(1).map(r=>({year:Number(g(r,'year'))||Number(parseDate(g(r,'date')).slice(0,4)),quarter:clean(g(r,'quarter')),company:clean(g(r,'company')),date:parseDate(g(r,'date')),account:clean(g(r,'account')),customer:clean(g(r,'customer')),invoice:clean(g(r,'invoice')),description:clean(g(r,'description')),revenue:num(g(r,'revenue')),incl:num(g(r,'incl')),country:clean(g(r,'country')),industry:clean(g(r,'industry')),group:clean(g(r,'group')),type:clean(g(r,'type')),supplier:clean(g(r,'supplier'))})).filter(r=>r.company&&r.company.toLowerCase()!=='totals'&&(r.invoice||r.date||r.revenue))}
function id(r){return [r.company,r.invoice,r.date,r.customer,r.description,r.revenue,r.group,r.type].join('|')}
async function importFiles(files){let seen=new Set(state.rows.map(id)),add=0,skip=0;for(let f of files){try{let rr=f.name.toLowerCase().endsWith('.xlsx')?await xlsx(f):csv(await f.text());for(let r of records(rr)){let k=id(r);if(seen.has(k)){skip++;continue}seen.add(k);state.rows.push(r);add++}}catch(e){alert(f.name+': '+e.message)}}await save();refresh();alert(`${add} regels toegevoegd, ${skip} dubbele regels overgeslagen.`)}
function vals(k){return [...new Set(state.rows.map(r=>clean(r[k])).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'nl'))}
function opts(id,k){let e=$(id),sel=new Set([...e.selectedOptions].map(o=>o.value));e.innerHTML=vals(k).map(v=>`<option ${sel.has(v)?'selected':''}>${esc(v)}</option>`).join('')}
function filters(){let f={start:$('filterStart').value,end:$('filterEnd').value,q:clean($('filterSearch').value).toLowerCase()};for(let [id,k] of Object.entries({filterCompany:'company',filterCustomer:'customer',filterAccount:'account',filterIndustry:'industry',filterProductGroup:'group',filterProductType:'type',filterCountry:'country',filterSupplier:'supplier'}))f[k]=[...$(id).selectedOptions].map(o=>o.value);return f}
function filtered(){let f=filters();return state.rows.filter(r=>{if(f.start&&r.date<f.start)return false;if(f.end&&r.date>f.end)return false;for(let k of ['company','customer','account','industry','group','type','country','supplier'])if(f[k].length&&!f[k].includes(r[k]))return false;if(f.q&&!`${r.customer} ${r.account} ${r.invoice} ${r.description}`.toLowerCase().includes(f.q))return false;return true})}
function agg(rows,k){let m={};rows.forEach(r=>{let x=r[k]||'Onbekend';m[x]=(m[x]||0)+r.revenue});return Object.entries(m).sort((a,b)=>b[1]-a[1])}
function bar(id,a,h=true,n=10){a=a.slice(0,n);Plotly.newPlot(id,[{type:'bar',x:h?a.map(x=>x[1]):a.map(x=>x[0]),y:h?a.map(x=>x[0]):a.map(x=>x[1]),orientation:h?'h':'v'}],{margin:{l:h?140:60,r:15,t:10,b:50},height:340,paper_bgcolor:'transparent',plot_bgcolor:'transparent'},{displayModeBar:false,responsive:true})}
function dashboard(rows){if(!rows.length){$('dashboardView').innerHTML='<div class="card">Geen gegevens binnen de filters.</div>';return}let total=rows.reduce((s,r)=>s+r.revenue,0),inv=new Set(rows.map(r=>r.company+'|'+r.invoice)).size,saas=rows.filter(r=>/saas|maintenance/i.test(r.type)).reduce((s,r)=>s+r.revenue,0),m={};rows.forEach(r=>{let k=r.date.slice(0,7);if(k)m[k]=(m[k]||0)+r.revenue});let mm=Object.entries(m).sort();$('dashboardView').innerHTML=`<div class="grid metrics"><div class="metric"><div class="label">Gerealiseerde omzet</div><div class="value">${eur(total)}</div></div><div class="metric"><div class="label">Facturen</div><div class="value">${inv}</div></div><div class="metric"><div class="label">Gem. omzet per factuur</div><div class="value">${eur(inv?total/inv:0)}</div></div><div class="metric"><div class="label">SaaS + maintenance</div><div class="value">${eur(saas)}</div></div></div><div class="card"><h3>Omzet per maand</h3><div id="monthlyChart"></div></div><div class="spacer"></div><div class="grid two"><div class="card"><h3>Top klanten</h3><div id="customerChart"></div></div><div class="card"><h3>Productgroepen</h3><div id="productChart"></div></div></div>`;Plotly.newPlot('monthlyChart',[{x:mm.map(x=>x[0]),y:mm.map(x=>x[1]),type:'scatter',mode:'lines+markers'}],{margin:{l:60,r:15,t:10,b:50},height:340,paper_bgcolor:'transparent',plot_bgcolor:'transparent'},{displayModeBar:false,responsive:true});bar('customerChart',agg(rows,'customer'));bar('productChart',agg(rows,'group'))}
function analysis(rows){$('analysisView').innerHTML='<div class="grid two"><div class="card"><h3>Omzet per industrie</h3><div id="industryChart"></div></div><div class="card"><h3>SN / SNC</h3><div id="companyChart"></div></div></div><div class="spacer"></div><div class="card"><h3>Omzet per producttype</h3><div id="typeChart"></div></div>';bar('industryChart',agg(rows,'industry'));bar('companyChart',agg(rows,'company'),false);bar('typeChart',agg(rows,'type'),true,20)}
function invoices(rows){let m=new Map();rows.forEach(r=>{let k=r.company+'|'+r.invoice;if(!m.has(k))m.set(k,{...r,revenue:0});m.get(k).revenue+=r.revenue});let a=[...m.values()].sort((x,y)=>y.date.localeCompare(x.date));$('invoicesView').innerHTML=`<div class="card"><div class="table-wrap"><table><thead><tr><th>Datum</th><th>Bedrijf</th><th>Factuur</th><th>Klant</th><th>Omzet</th><th>Productgroep</th><th>Producttype</th></tr></thead><tbody>${a.slice(0,1000).map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.company)}</td><td>${esc(r.invoice)}</td><td>${esc(r.customer||r.account)}</td><td class="num">${eur(r.revenue)}</td><td>${esc(r.group)}</td><td>${esc(r.type)}</td></tr>`).join('')}</tbody></table></div></div>`}
function manage(){ $('importView').innerHTML=`<div class="grid two"><div class="card"><h3>Maandelijkse import</h3><p class="hint">Excel (.xlsx) of CSV. Bij Excel wordt automatisch tabblad Combined gebruikt.</p><div id="dropzone" class="dropzone"><h3>Sleep bestanden hierheen</h3><p>of kies bestanden</p><button id="chooseFiles">Bestanden kiezen</button></div><div class="callout success"><strong>Privacy:</strong> gegevens worden lokaal in deze browser verwerkt en opgeslagen.</div></div><div class="card"><h3>Lokale database</h3><p>${state.rows.length} factuurregels in deze browser.</p><div class="toolbar"><button id="backup">Backup downloaden</button><button id="restore" class="secondary">Backup terugzetten</button><button id="wipe" class="danger">Database wissen</button></div></div></div>`;$('chooseFiles').onclick=()=>$('filePicker').click();let z=$('dropzone');['dragenter','dragover'].forEach(e=>z.addEventListener(e,x=>{x.preventDefault();z.classList.add('drag')}));['dragleave','drop'].forEach(e=>z.addEventListener(e,x=>{x.preventDefault();z.classList.remove('drag')}));z.ondrop=e=>importFiles([...e.dataTransfer.files]);$('backup').onclick=()=>download(new Blob([JSON.stringify(state)],{type:'application/json'}),'SN-revenue-backup.json');$('restore').onclick=()=>$('backupPicker').click();$('wipe').onclick=async()=>{if(confirm('Alle lokale omzetdata wissen?')){state={rows:[],tags:{}};await save();refresh()}}}
function download(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportCsv(){let h=['Year','Quarter','Company','Date','Account','Customer','invoice nr','Description','Revenue (EUR)','Country','Industry','Product group','Product Type','Supplier'],lines=[h.join(';')];filtered().forEach(r=>lines.push([r.year,r.quarter,r.company,r.date,r.account,r.customer,r.invoice,r.description,r.revenue,r.country,r.industry,r.group,r.type,r.supplier].map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')));download(new Blob(['\uFEFF'+lines.join('\r\n')],{type:'text/csv'}),'omzet-export.csv')}
function render(){let r=filtered();document.querySelectorAll('.view').forEach(e=>e.classList.add('hidden'));if(!state.rows.length&&view!=='import'){$('emptyState').classList.remove('hidden');return}$('emptyState').classList.add('hidden');$(`${view}View`).classList.remove('hidden');if(view==='dashboard')dashboard(r);else if(view==='analysis')analysis(r);else if(view==='invoices')invoices(r);else manage()}
function refresh(){for(let [id,k] of Object.entries({filterCompany:'company',filterCustomer:'customer',filterAccount:'account',filterIndustry:'industry',filterProductGroup:'group',filterProductType:'type',filterCountry:'country',filterSupplier:'supplier'}))opts(id,k);let d=state.rows.map(r=>r.date).filter(Boolean).sort();if(d.length){if(!$('filterStart').value)$('filterStart').value=d[0];if(!$('filterEnd').value)$('filterEnd').value=d[d.length-1]}render()}
async function init(){await load();document.querySelectorAll('#mainNav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('#mainNav button').forEach(x=>x.classList.toggle('active',x===b));let t={dashboard:'Dashboard',analysis:'Analyses',invoices:'Facturen & tags',import:'Import & beheer'};$('pageTitle').textContent=t[view];render()});['filterCompany','filterCustomer','filterAccount','filterIndustry','filterProductGroup','filterProductType','filterCountry','filterSupplier','filterStart','filterEnd'].forEach(id=>$(id).onchange=render);$('filterSearch').oninput=render;$('clearFilters').onclick=()=>{document.querySelectorAll('.sidebar select[multiple]').forEach(s=>[...s.options].forEach(o=>o.selected=false));$('filterSearch').value='';$('filterStart').value='';$('filterEnd').value='';refresh()};$('quickImport').onclick=()=>{view='import';render()};$('emptyImport').onclick=()=>{view='import';render()};$('exportFiltered').onclick=exportCsv;$('filePicker').onchange=async e=>{if(e.target.files.length)await importFiles([...e.target.files]);e.target.value=''};$('backupPicker').onchange=async e=>{if(e.target.files[0]){let x=JSON.parse(await e.target.files[0].text());if(Array.isArray(x.rows)){state=x;await save();refresh()}}e.target.value=''};refresh()}
window.addEventListener('DOMContentLoaded',init);
